apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft # Ccnsistent namespace with deployment
spec:
  type: LoadBalancer # expose the service externally
  ports:
  - port: 25565 # port exposed by the service
    targetPort: 25565 # port mapped inside the pod
    nodePort: 30000 # NodePort for external access
  selector:
    app: minecraft # route traffic to pods with this label
