apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: minecraft
  name: minecraft
spec:
  ports:
    - name: "25565"
      port: 25565
      targetPort: 25565
  selector:
    io.kompose.service: minecraft
