apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: minecraft
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: minecraft
    spec:
      containers:
        - env:
            - name: EULA
              value: "TRUE"
          image: itzg/minecraft-server
          name: minecraft
          ports:
            - containerPort: 25565
              protocol: TCP
          resources:
            limits:
              memory: "1610612736"
          volumeMounts:
            - mountPath: /data
              name: minecraft-claim0
      restartPolicy: Always
      volumes:
        - name: minecraft-claim0
          persistentVolumeClaim:
            claimName: minecraft-claim0
